---
- name: Install dependencies
  become: yes
  apt:
    update_cache: yes
    name:
      - zsh
      - git

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Get zsh path
  shell: which zsh
  register: zsh_path

- name: Change user shell
  become: yes
  user:
    name: "{{ lookup('env','USER') }}"
    shell: "{{ zsh_path.stdout }}"

- name: Copy zshrc file
  file:
    src: "{{ role_path }}/files/zshrc"
    path: "{{ lookup('env','HOME') }}/.zshrc"
    state: link
    force: yes

- name: Debug message
  debug:
    msg: "Please log out and login again to see changed shell"
